// const mongoose = require("mongoose");

// const inventoryHealthSchema = new mongoose.Schema({
//   SKU: String,
//   Country: String,
//   afn_warehouse_quantity: Number,
//   afn_fulfillable_quantity: Number,
//   afn_unsellable_quantity: Number,
//   afn_reserved_quantity: Number,
//   afn_total_quantity: Number,
//   afn_inbound_working_quantity: Number,
//   afn_inbound_shipped_quantity: Number,
//   afn_inbound_receiving_quantity: Number,
//   afn_researching_quantity: Number,
//   afn_reserved_future_supply: Number,
//   afn_future_supply_buyable: Number,
//   Amazon_Reserved: Number,
//   Customer_reserved: Number,
//   FC_Transfer: Number,
//   FC_Processing: Number,
//   Date: String, // Will be formatted as 'YYYY-MM-DD'
//   healthy_inventory_level: String,
//   days_of_supply: Number,
//   inv_age_0_to_30_days: Number,
//   inv_age_31_to_60_days: Number,
//   inv_age_61_to_90_days: Number,
//   inv_age_91_to_180_days: Number,
//   inv_age_181_to_270_days: Number,
//   inv_age_271_to_365_days: Number,
//   inv_age_365_plus_days: Number,
//   units_shipped_t7: Number,
//   units_shipped_t30: Number,
//   units_shipped_t60: Number,
//   units_shipped_t90: Number,
//   recommended_action: String,
//   estimated_cost_savings_of_recommended_actions: Number,
//   estimated_storage_cost_next_month: Number,
//   estimated_ais_331_365_days: Number,
//   estimated_ais_365_plus_days: Number,
//   quantity_to_be_charged_ais_241_270_days: Number,
//   estimated_ais_241_270_days: Number,
//   quantity_to_be_charged_ais_271_300_days: Number,
//   estimated_ais_271_300_days: Number,
//   quantity_to_be_charged_ais_301_330_days: Number,
//   estimated_ais_301_330_days: Number,
//   Days_In_Stock: Number,
//   Total_Days: Number,
//   InStock_Rate: Number,
//   InStock_Rate_Percent: Number,
//   Last_30_Days_Unit_Sold: Number,
//   Avg_Unit_Sold_Qty: Number,
//   MTQ: Number,
//   Stock_Status: String,
// });

// module.exports = mongoose.model("InventoryHealth", inventoryHealthSchema);




const mongoose = require("mongoose");

const inventoryHealthSchema = new mongoose.Schema({
  Date: String, // formatted as 'YYYY-MM-DD'
  Country: String,
  SKU: String,
  Product_Category: String,
  Product_Name: String,
  Product_COGS: String,
  Type: String,
  WH_Stock_Value: Number,
  Sellable_Stock_Value: Number,
  afn_warehouse_quantity: Number,
  afn_fulfillable_quantity: Number,
  afn_unsellable_quantity: Number,
  afn_reserved_quantity: Number,
  afn_total_quantity: Number,
  Amazon_Reserved: Number,
  Customer_reserved: Number,
  FC_Transfer: Number,
  FC_Processing: Number,
  days_of_supply: Number,
  Days_In_Stock: Number,
  Total_Days: Number,
  InStock_Rate: Number,
  InStock_Rate_Percent: Number,
  Last_30_Days_Unit_Sold: Number,
  Avg_Unit_Sold_Qty: Number,
  MTQ_overstock: Number,
  MTQ_understock: Number,
  Stock_Status: String,
  inv_age_0_to_30_days: Number,
  inv_age_31_to_60_days: Number,
  inv_age_61_to_90_days: Number,
  inv_age_91_to_180_days: Number,
  inv_age_181_to_270_days: Number,
  inv_age_271_to_365_days: Number,
  inv_age_365_plus_days: Number,
  units_shipped_t7: Number,
  units_shipped_t30: Number,
  units_shipped_t60: Number,
  units_shipped_t90: Number,
  estimated_storage_cost_next_month: Number,
  quantity_to_be_charged_ais_241_270_days: Number,
  estimated_ais_241_270_days: Number,
  quantity_to_be_charged_ais_271_300_days: Number,
  estimated_ais_271_300_days: Number,
  quantity_to_be_charged_ais_301_330_days: Number,
  estimated_ais_301_330_days: Number,
  estimated_cost_savings_of_recommended_actions: Number,
  estimated_ais_331_365_days: Number,
  estimated_ais_365_plus_days: Number,
});

module.exports = mongoose.model("InventoryHealth", inventoryHealthSchema);
